server:
  port: 8080
  servlet:
    context-path: /feihua

spring:
  application:
    name: nso-sy
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/nso_sy?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&connectTimeout=60000&socketTimeout=60000
    username: admin
    password: ZZPass2019!
    druid:
      initialSize: 5
      minIdle: 20
      maxActive: 100
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 10
      filters: stat
      default-transaction-isolation: 2
      async-init: true
      connection-error-retry-attempts: 3
      keep-alive: false
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
    schema: classpath:mybatis/sql/schema.sql
    initialization-mode: always
    platform: all
  jackson:
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
      ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER: true
    default-property-inclusion: non_null
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      #      id-type: ASSIGN_ID
      #      field-strategy: not_empty
      id-type: auto
      db-type: dm
    banner: true
#  打印SQL语句用的，建议不删除
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  #  开启压缩
  compression:
    request:
      enabled: true
    response:
      enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: false
  client:
    config:
      DeviceFeignClient:
        connectTimeout: 20000
        readTimeout: 100000
wechat:
  appid: "wxa0e3ba1698f04ad5"
  secret: "10db9de0213ec489dbbd1079c4ac074f"
  grantType: "authorization_code"

logging:
  config: classpath:log/logback.xml
  level:
    cn.pml.cnos.nso.common.http: debug
